### ISSUE TITLE
Please add svg-tileserver to crates.io

### ISSUE THREAD

**Issue by LaurentBonnaud** [GaspardCulis/svg-tileserver#1]
Hi,
I tried to install this software with cargo, but failed:
```
$ cargo install svg-tileserver 
    Updating crates.io index
error: could not find `svg-tileserver` in registry `crates-io` with version `*`
```
Would it be possible to add it to crates.io?

**Comment by GaspardCulis** [comment]
Hi, 
I initially wasn't sure if anyone would be interested in this project so I decided not to publish it on crates.io, but it seems like it's not the case anymore! Here is the newly published package: 

[https://crates.io/crates/svg-tileserver](https://crates.io/crates/svg-tileserver)

**Comment by LaurentBonnaud** [comment]
It works, thanks!
